import type {
  MonthlyEmission,
  ScopeDetail,
  EsrsStandard,
  EsrsRadialData,
  Activity,
  PricingPlan,
  AiSuggestion,
} from "./types";

export const monthlyEmissions: MonthlyEmission[] = [
  { month: "Jan", scope1: 120, scope2: 85, scope3: 340 },
  { month: "Fév", scope1: 115, scope2: 82, scope3: 325 },
  { month: "Mar", scope1: 130, scope2: 90, scope3: 360 },
  { month: "Avr", scope1: 110, scope2: 78, scope3: 310 },
  { month: "Mai", scope1: 105, scope2: 75, scope3: 295 },
  { month: "Jun", scope1: 100, scope2: 72, scope3: 280 },
  { month: "Jul", scope1: 95, scope2: 70, scope3: 270 },
  { month: "Aoû", scope1: 98, scope2: 68, scope3: 265 },
  { month: "Sep", scope1: 108, scope2: 74, scope3: 290 },
  { month: "Oct", scope1: 112, scope2: 76, scope3: 300 },
  { month: "Nov", scope1: 118, scope2: 80, scope3: 315 },
  { month: "Déc", scope1: 125, scope2: 84, scope3: 335 },
];

export const scopeDetails: ScopeDetail[] = [
  {
    id: 1,
    name: "Scope 1",
    description: "Émissions directes — combustion, flotte véhicules, réfrigérants",
    total: 1336,
    unit: "tCO₂e",
    trend: -8.2,
    categories: [
      { name: "Combustion fixe", value: 520, color: "#059669" },
      { name: "Flotte véhicules", value: 380, color: "#34D399" },
      { name: "Réfrigérants", value: 210, color: "#6EE7B7" },
      { name: "Procédés", value: 226, color: "#A7F3D0" },
    ],
  },
  {
    id: 2,
    name: "Scope 2",
    description: "Émissions indirectes — électricité, chauffage, vapeur",
    total: 934,
    unit: "tCO₂e",
    trend: -12.5,
    categories: [
      { name: "Électricité", value: 580, color: "#0891B2" },
      { name: "Chauffage urbain", value: 220, color: "#22D3EE" },
      { name: "Vapeur", value: 134, color: "#67E8F9" },
    ],
  },
  {
    id: 3,
    name: "Scope 3",
    description: "Autres émissions indirectes — chaîne de valeur amont & aval",
    total: 3685,
    unit: "tCO₂e",
    trend: -3.1,
    categories: [
      { name: "Achats biens & services", value: 1250, color: "#7C3AED" },
      { name: "Transport amont", value: 680, color: "#8B5CF6" },
      { name: "Déplacements pro", value: 420, color: "#A78BFA" },
      { name: "Déchets", value: 310, color: "#C4B5FD" },
      { name: "Transport aval", value: 525, color: "#DDD6FE" },
      { name: "Utilisation produits", value: 500, color: "#EDE9FE" },
    ],
  },
];

export const esrsStandards: EsrsStandard[] = [
  {
    id: "ESRS E1",
    name: "Changement climatique",
    fullName: "ESRS E1 — Changement climatique",
    progress: 85,
    status: "in_progress",
    description: "Atténuation, adaptation, énergie",
    dataPoints: 48,
    completedPoints: 41,
  },
  {
    id: "ESRS E2",
    name: "Pollution",
    fullName: "ESRS E2 — Pollution",
    progress: 72,
    status: "in_progress",
    description: "Air, eau, sol, substances préoccupantes",
    dataPoints: 32,
    completedPoints: 23,
  },
  {
    id: "ESRS E3",
    name: "Eau & ressources marines",
    fullName: "ESRS E3 — Eau et ressources marines",
    progress: 60,
    status: "in_progress",
    description: "Consommation, rejets, écosystèmes marins",
    dataPoints: 28,
    completedPoints: 17,
  },
  {
    id: "ESRS E4",
    name: "Biodiversité",
    fullName: "ESRS E4 — Biodiversité et écosystèmes",
    progress: 45,
    status: "in_progress",
    description: "Impacts, dépendances, zones sensibles",
    dataPoints: 36,
    completedPoints: 16,
  },
  {
    id: "ESRS E5",
    name: "Économie circulaire",
    fullName: "ESRS E5 — Utilisation des ressources et économie circulaire",
    progress: 55,
    status: "in_progress",
    description: "Flux de ressources, déchets, recyclage",
    dataPoints: 24,
    completedPoints: 13,
  },
  {
    id: "ESRS S1",
    name: "Effectifs propres",
    fullName: "ESRS S1 — Effectifs de l'entreprise",
    progress: 90,
    status: "compliant",
    description: "Conditions de travail, égalité, santé-sécurité",
    dataPoints: 52,
    completedPoints: 47,
  },
  {
    id: "ESRS S2",
    name: "Travailleurs chaîne",
    fullName: "ESRS S2 — Travailleurs de la chaîne de valeur",
    progress: 40,
    status: "in_progress",
    description: "Conditions, droits, travail forcé",
    dataPoints: 30,
    completedPoints: 12,
  },
  {
    id: "ESRS S3",
    name: "Communautés",
    fullName: "ESRS S3 — Communautés affectées",
    progress: 30,
    status: "not_started",
    description: "Droits des communautés, impact territorial",
    dataPoints: 22,
    completedPoints: 7,
  },
  {
    id: "ESRS S4",
    name: "Consommateurs",
    fullName: "ESRS S4 — Consommateurs et utilisateurs finaux",
    progress: 35,
    status: "not_started",
    description: "Sécurité, vie privée, inclusion",
    dataPoints: 20,
    completedPoints: 7,
  },
  {
    id: "ESRS G1",
    name: "Gouvernance",
    fullName: "ESRS G1 — Conduite des affaires",
    progress: 78,
    status: "in_progress",
    description: "Éthique, corruption, lobbying, paiements",
    dataPoints: 26,
    completedPoints: 20,
  },
  {
    id: "ESRS 1",
    name: "Exigences générales",
    fullName: "ESRS 1 — Exigences générales",
    progress: 95,
    status: "compliant",
    description: "Principes, périmètre, double matérialité",
    dataPoints: 18,
    completedPoints: 17,
  },
  {
    id: "ESRS 2",
    name: "Infos générales",
    fullName: "ESRS 2 — Informations générales",
    progress: 88,
    status: "in_progress",
    description: "Stratégie, gouvernance, gestion des impacts",
    dataPoints: 42,
    completedPoints: 37,
  },
];

export const esrsRadialData: EsrsRadialData[] = [
  { subject: "E1 Climat", value: 85, fullMark: 100 },
  { subject: "E2 Pollution", value: 72, fullMark: 100 },
  { subject: "E3 Eau", value: 60, fullMark: 100 },
  { subject: "E4 Biodiv.", value: 45, fullMark: 100 },
  { subject: "E5 Circulaire", value: 55, fullMark: 100 },
  { subject: "S1 Effectifs", value: 90, fullMark: 100 },
  { subject: "S2 Chaîne", value: 40, fullMark: 100 },
  { subject: "S3 Communautés", value: 30, fullMark: 100 },
  { subject: "S4 Consomm.", value: 35, fullMark: 100 },
  { subject: "G1 Gouvernance", value: 78, fullMark: 100 },
];

export const recentActivity: Activity[] = [
  {
    id: 1,
    type: "upload",
    title: "Données Scope 2 importées",
    description: "Factures électricité T4 2025 — 14 sites",
    time: "Il y a 2h",
    icon: "upload",
  },
  {
    id: 2,
    type: "validation",
    title: "ESRS E1 validé par l'auditeur",
    description: "48 data points vérifiés — conforme",
    time: "Il y a 5h",
    icon: "check-circle",
  },
  {
    id: 3,
    type: "alert",
    title: "Anomalie détectée — Scope 3",
    description: "Transport amont : +23% vs. moyenne sectorielle",
    time: "Hier",
    icon: "alert-triangle",
  },
  {
    id: 4,
    type: "report",
    title: "Rapport CSRD Q4 généré",
    description: "PDF exporté — prêt pour soumission",
    time: "Hier",
    icon: "file-text",
  },
  {
    id: 5,
    type: "upload",
    title: "Données déchets importées",
    description: "Registre déchets 2025 — 8 catégories",
    time: "Il y a 2j",
    icon: "upload",
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    price: "490",
    period: "/ mois",
    description: "Pour les PME débutant leur reporting ESG",
    features: [
      "Scope 1 & 2",
      "3 ESRS de base",
      "1 utilisateur",
      "Export PDF",
      "Support email",
    ],
    highlighted: false,
  },
  {
    id: "business",
    name: "Business",
    price: "1 290",
    period: "/ mois",
    description: "Pour les ETI avec obligations CSRD",
    features: [
      "Scope 1, 2 & 3",
      "12 ESRS complets",
      "5 utilisateurs",
      "Copilote IA",
      "Audit trail",
      "API & intégrations",
      "Support prioritaire",
    ],
    highlighted: true,
    badge: "Populaire",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "2 990",
    period: "/ mois",
    description: "Pour les grands groupes multi-sites",
    features: [
      "Scope 1, 2, 3 + CBAM",
      "12 ESRS + Taxonomie",
      "Utilisateurs illimités",
      "Copilote IA avancé",
      "SBTi trajectoire",
      "Multi-sites & filiales",
      "SSO & RBAC",
      "Onboarding dédié",
    ],
    highlighted: false,
  },
  {
    id: "sovereign",
    name: "Souverain",
    price: "Sur devis",
    period: "",
    description: "Hébergement souverain, conformité renforcée",
    features: [
      "Tout Enterprise",
      "Cloud souverain SecNumCloud",
      "Données hébergées en France",
      "SLA 99,95%",
      "Auditabilité complète",
      "Accompagnement réglementaire",
    ],
    highlighted: false,
    badge: "🇫🇷 Souverain",
  },
];

export const aiSuggestions: AiSuggestion[] = [
  {
    id: 1,
    title: "Optimiser la flotte véhicules",
    description:
      "Remplacer 30% de la flotte diesel par des véhicules électriques réduirait le Scope 1 de ~114 tCO₂e/an.",
    impact: "high",
    category: "Scope 1",
  },
  {
    id: 2,
    title: "Contrat énergie verte",
    description:
      "Passer à un fournisseur 100% renouvelable pour 5 sites principaux — réduction Scope 2 estimée : -40%.",
    impact: "high",
    category: "Scope 2",
  },
  {
    id: 3,
    title: "Politique télétravail",
    description:
      "2 jours/semaine de télétravail réduiraient les déplacements domicile-travail de ~85 tCO₂e/an.",
    impact: "medium",
    category: "Scope 3",
  },
  {
    id: 4,
    title: "Fournisseurs éco-responsables",
    description:
      "Intégrer des critères ESG dans les appels d'offres pour réduire les émissions Scope 3 amont de 15%.",
    impact: "medium",
    category: "Scope 3",
  },
];

export const aiResponses: Record<string, string> = {
  default:
    "Je suis le Copilote CarbonCo, votre assistant IA spécialisé en ESG et CSRD. Je peux vous aider à analyser vos émissions, comprendre les normes ESRS, et optimiser votre stratégie carbone. Que souhaitez-vous savoir ?",
  scope:
    "Vos émissions totales s'élèvent à **5 955 tCO₂e** sur les 12 derniers mois.\n\n- **Scope 1** : 1 336 tCO₂e (22%) — en baisse de 8,2%\n- **Scope 2** : 934 tCO₂e (16%) — en baisse de 12,5%\n- **Scope 3** : 3 685 tCO₂e (62%) — en baisse de 3,1%\n\nLe Scope 3 reste votre principal levier de réduction. Je recommande de cibler les achats de biens & services (1 250 tCO₂e) et le transport amont (680 tCO₂e).",
  esrs: "Votre conformité ESRS globale est de **63%**.\n\n**Points forts :**\n- ESRS 1 (Exigences générales) : 95% ✅\n- ESRS S1 (Effectifs) : 90% ✅\n\n**Priorités :**\n- ESRS S3 (Communautés) : 30% — démarrez la consultation des parties prenantes\n- ESRS S4 (Consommateurs) : 35% — collectez les données de satisfaction client\n- ESRS S2 (Chaîne de valeur) : 40% — lancez un questionnaire fournisseurs",
  cbam: "Le **CBAM** (Carbon Border Adjustment Mechanism) entre en phase transitoire.\n\n**Actions requises :**\n1. Identifier les importations couvertes (acier, aluminium, ciment, engrais, électricité, hydrogène)\n2. Collecter les données d'émissions intégrées auprès de vos fournisseurs hors-UE\n3. Déclarer trimestriellement via le registre CBAM\n\nVotre exposition estimée : **~240 tCO₂e** sur les importations d'acier et d'aluminium.",
  taxonomie:
    "La **Taxonomie européenne** définit 6 objectifs environnementaux.\n\nVos activités éligibles représentent **42% du CA** :\n- Atténuation climat : 35% aligné\n- Adaptation climat : 28% aligné\n- Eau : en cours d'évaluation\n\n**Prochaine étape** : documenter les critères DNSH (Do No Significant Harm) pour vos 3 principales activités éligibles.",
};
